from datetime import datetime
from database import db
from database.models import CommunicationSummary
import random

async def seed_summaries(lead_ids):
    """Seed the communication summaries collection with initial data"""
    try:
        summaries_collection = db.get_db().communication_summaries
        
        if not lead_ids:
            print("No lead_ids provided. Please seed leads first.")
            return []
        
        # Sample summary data
        summaries = []
        for lead_id in lead_ids:
            # Generate a simple embedding (in a real system, this would be generated by an ML model)
            embedding = [random.uniform(-1, 1) for _ in range(384)]  # Using 384 dimensions as an example
            
            summary = CommunicationSummary(
                lead_id=str(lead_id),
                summary="Initial contact established with positive response. Product features discussed and interest shown in implementation timeline. Follow-up meeting scheduled.",
                key_points=[
                    "Initial outreach successful",
                    "Product features well received",
                    "Implementation timeline discussed",
                    "Follow-up meeting planned"
                ],
                sentiment="positive",  # Using string as per model
                embedding=embedding,
                created_at=datetime.utcnow()
            )
            summaries.append(summary)
        
        if not summaries:
            print("No summaries created. Check lead_ids.")
            return []
            
        # Clear existing data
        await summaries_collection.delete_many({})
        
        # Insert new data
        result = await summaries_collection.insert_many([summary.model_dump() for summary in summaries])
        print(f"Successfully seeded {len(result.inserted_ids)} communication summaries")
        
        return result.inserted_ids
    except Exception as e:
        print(f"Error seeding communication summaries: {str(e)}")
        return [] 